# Generated by Django 6.0.4 on 2026-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('square_feet', models.IntegerField()),
                ('total_bedrooms', models.IntegerField()),
                ('total_rooms', models.IntegerField()),
                ('utilities_description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rent', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('advance_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
